In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Organizando e entendendo dados de Horas-Aula
## 2016 - 2020

In [2]:
ha16 = pd.read_excel("/content/horas_aula_2016.xlsX", index_col=False, header=None, squeeze=True)
ha16

                                                      0   ...   27
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Número médio de Horas-Aula Diária na Creche, P...  ...  NaN
...                                                  ...  ...  ...
65819                                               2016  ...  4.9
65820                                               2016  ...   --
65821                                                NaN  ...  NaN
65822         Fonte: Censo da Educação Básica 2016/INEP.  ...  NaN
65823  Nota: Para este indicador são consideradas ape...  ...  NaN

[65824 rows x 28 columns]

In [3]:
ha16New = ha16
ha16New.columns = ha16.iloc[8]
ha16New = ha16.drop(labels=[0,1,2,3,4,5,6,7,8,65821,65822,65823], axis=0)
ha16New = ha16New.replace("--", np.nan, regex=True)
ha16New.reset_index(drop=True, inplace=True)
ha16New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2016         Norte    RO  ...      4.6     NaN     NaN
1              2016         Norte    RO  ...      4.6     NaN     NaN
2              2016         Norte    RO  ...      NaN     NaN     NaN
3              2016         Norte    RO  ...      4.6     NaN     NaN
4              2016         Norte    RO  ...      4.6     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65807          2016  Centro-Oeste    DF  ...      5.8     5.5     NaN
65808          2016  Centro-Oeste    DF  ...      6.0     NaN     NaN
65809          2016  Centro-Oeste    DF  ...      5.0     NaN     4.9
65810          2016  Centro-Oeste    DF  ...      5.0     NaN     4.9
65811          2016  Centro-Oeste    DF  ...      5.5     NaN     NaN

[65812 rows x 28 columns]

In [4]:
ha16New.dtypes

8
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
CO_MUNICIPIO      int64
NO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
HAD_INF         float64
HAD_CRE         float64
HAD_PRE         float64
HAD_FUN         float64
HAD_F14         float64
HAD_F58         float64
HAD_F00         float64
HAD_F01         float64
HAD_F02         float64
HAD_F03         float64
HAD_F04         float64
HAD_F05         float64
HAD_F06         float64
HAD_F07         float64
HAD_F08         float64
HAD_MED         float64
HAD_M01         float64
HAD_M02         float64
HAD_M03         float64
HAD_M04         float64
HAD_MNS         float64
dtype: object

In [5]:
ha17 = pd.read_excel("/content/horas_aula_2017.xlsX", index_col=False, header=None, squeeze=True)
ha17

                                                      0   ...   27
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3        Média de Horas-Aula Diária por município - 2017  ...  NaN
4      Número médio de Horas-Aula Diária na Creche, P...  ...  NaN
...                                                  ...  ...  ...
65853                                               2017  ...   --
65854                                               2017  ...   --
65855                                                NaN  ...  NaN
65856         Fonte: Censo da Educação Básica 2017/INEP.  ...  NaN
65857  Nota: Para este indicador são consideradas ape...  ...  NaN

[65858 rows x 28 columns]

In [6]:
ha17New = ha17
ha17New.columns = ha16.iloc[8]
ha17New = ha17.drop(labels=[0,1,2,3,4,5,6,7,8,65855,65856,65857], axis=0)
ha17New = ha17New.replace("--", np.nan, regex=True)
ha17New.reset_index(drop=True, inplace=True)
ha17New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2017         Norte    RO  ...      6.3     NaN     NaN
1              2017         Norte    RO  ...      6.3     NaN     NaN
2              2017         Norte    RO  ...      NaN     NaN     NaN
3              2017         Norte    RO  ...      6.3     NaN     NaN
4              2017         Norte    RO  ...      6.3     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65841          2017  Centro-Oeste    DF  ...      5.6     NaN     NaN
65842          2017  Centro-Oeste    DF  ...      6.0     NaN     NaN
65843          2017  Centro-Oeste    DF  ...      5.0     NaN     NaN
65844          2017  Centro-Oeste    DF  ...      5.0     NaN     NaN
65845          2017  Centro-Oeste    DF  ...      4.9     NaN     NaN

[65846 rows x 28 columns]

In [7]:
ha17New.dtypes

8
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
CO_MUNICIPIO      int64
NO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
HAD_INF         float64
HAD_CRE         float64
HAD_PRE         float64
HAD_FUN         float64
HAD_F14         float64
HAD_F58         float64
HAD_F00         float64
HAD_F01         float64
HAD_F02         float64
HAD_F03         float64
HAD_F04         float64
HAD_F05         float64
HAD_F06         float64
HAD_F07         float64
HAD_F08         float64
HAD_MED         float64
HAD_M01         float64
HAD_M02         float64
HAD_M03         float64
HAD_M04         float64
HAD_MNS         float64
dtype: object

In [8]:
ha18 = pd.read_excel("/content/horas_aula_2018.xlsx", index_col=False, header=None, squeeze=True)
ha18

                                                      0   ...   27
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3        Média de Horas-Aula Diária por município - 2018  ...  NaN
4      Número médio de Horas-Aula Diária na Creche, P...  ...  NaN
...                                                  ...  ...  ...
65779                                               2018  ...  NaN
65780                                               2018  ...  NaN
65781                                                NaN  ...  NaN
65782         Fonte: Censo da Educação Básica 2018/INEP.  ...  NaN
65783  Nota: Não inclui matrículas em turmas de educa...  ...  NaN

[65784 rows x 28 columns]

In [9]:
ha18New = ha18
ha18New.columns = ha17.iloc[8]
ha18New = ha18.drop(labels=[0,1,2,3,4,5,6,7,8,65781,65782,65783], axis=0)
ha18New = ha18New.replace("--", np.nan, regex=True)
ha18New.reset_index(drop=True, inplace=True)
ha18New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2018         Norte    RO  ...      4.6     NaN     NaN
1              2018         Norte    RO  ...      4.6     NaN     NaN
2              2018         Norte    RO  ...      4.0     NaN     NaN
3              2018         Norte    RO  ...      4.6     NaN     NaN
4              2018         Norte    RO  ...      4.6     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65767          2018  Centro-Oeste    DF  ...      5.6     NaN     5.3
65768          2018  Centro-Oeste    DF  ...      5.8     NaN     NaN
65769          2018  Centro-Oeste    DF  ...      5.0     NaN     NaN
65770          2018  Centro-Oeste    DF  ...      5.0     NaN     NaN
65771          2018  Centro-Oeste    DF  ...      5.5     NaN     NaN

[65772 rows x 28 columns]

In [10]:
ha18New.dtypes

8
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
CO_MUNICIPIO      int64
NO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
HAD_INF         float64
HAD_CRE         float64
HAD_PRE         float64
HAD_FUN         float64
HAD_F14         float64
HAD_F58         float64
HAD_F00         float64
HAD_F01         float64
HAD_F02         float64
HAD_F03         float64
HAD_F04         float64
HAD_F05         float64
HAD_F06         float64
HAD_F07         float64
HAD_F08         float64
HAD_MED         float64
HAD_M01         float64
HAD_M02         float64
HAD_M03         float64
HAD_M04         float64
HAD_MNS         float64
dtype: object

In [11]:
ha19 = pd.read_excel("/content/horas_aula_2019.xlsx", index_col=False, header=None, squeeze=True)
ha19

                                                      0   ...   27
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3        Média de Horas-Aula Diária por município - 2019  ...  NaN
4      Número médio de Horas-Aula Diária na Creche, P...  ...  NaN
...                                                  ...  ...  ...
65694                                               2019  ...  NaN
65695                                               2019  ...  NaN
65696                                                NaN  ...  NaN
65697         Fonte: Censo da Educação Básica 2019/INEP.  ...  NaN
65698  Nota: Não inclui matrículas em turmas de educa...  ...  NaN

[65699 rows x 28 columns]

In [12]:
ha19New = ha19
ha19New.columns = ha17.iloc[8]
ha19New = ha19.drop(labels=[0,1,2,3,4,5,6,7,8,65696,65697,65698], axis=0)
ha19New = ha19New.replace("--", np.nan, regex=True)
ha19New.reset_index(drop=True, inplace=True)
ha19New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2019         Norte    RO  ...      5.5     NaN     NaN
1              2019         Norte    RO  ...      5.6     NaN     NaN
2              2019         Norte    RO  ...      4.0     NaN     NaN
3              2019         Norte    RO  ...      5.5     NaN     NaN
4              2019         Norte    RO  ...      5.6     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65682          2019  Centro-Oeste    DF  ...      5.6     NaN     5.3
65683          2019  Centro-Oeste    DF  ...      5.8     NaN     NaN
65684          2019  Centro-Oeste    DF  ...      5.0     NaN     NaN
65685          2019  Centro-Oeste    DF  ...      5.0     NaN     NaN
65686          2019  Centro-Oeste    DF  ...      5.7     NaN     NaN

[65687 rows x 28 columns]

In [13]:
ha19New.dtypes

8
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
CO_MUNICIPIO      int64
NO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
HAD_INF         float64
HAD_CRE         float64
HAD_PRE         float64
HAD_FUN         float64
HAD_F14         float64
HAD_F58         float64
HAD_F00         float64
HAD_F01         float64
HAD_F02         float64
HAD_F03         float64
HAD_F04         float64
HAD_F05         float64
HAD_F06         float64
HAD_F07         float64
HAD_F08         float64
HAD_MED         float64
HAD_M01         float64
HAD_M02         float64
HAD_M03         float64
HAD_M04         float64
HAD_MNS         float64
dtype: object

In [14]:
ha20 = pd.read_excel("/content/horas_aula_2020.xlsx", index_col=False, header=None, squeeze=True)
ha20

                                                      0   ...   27
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3        Média de Horas-Aula Diária por município - 2020  ...  NaN
4      Número médio de Horas-Aula Diária na Creche, P...  ...  NaN
...                                                  ...  ...  ...
65638                                               2020  ...   --
65639                                               2020  ...   --
65640                                                NaN  ...  NaN
65641         Fonte: Censo da Educação Básica 2020/INEP.  ...  NaN
65642  Nota: Não inclui matrículas em turmas de educa...  ...  NaN

[65643 rows x 28 columns]

In [15]:
ha20New = ha20
ha20New.columns = ha17.iloc[8]
ha20New = ha20.drop(labels=[0,1,2,3,4,5,6,7,8,65640,65641,65642], axis=0)
ha20New = ha20New.replace("--", np.nan, regex=True)
ha20New.reset_index(drop=True, inplace=True)
ha20New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2020         Norte    RO  ...      5.2     NaN     NaN
1              2020         Norte    RO  ...      5.3     NaN     NaN
2              2020         Norte    RO  ...      4.0     NaN     NaN
3              2020         Norte    RO  ...      5.2     NaN     NaN
4              2020         Norte    RO  ...      5.3     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65626          2020  Centro-Oeste    DF  ...      5.6     NaN     5.3
65627          2020  Centro-Oeste    DF  ...      5.8     NaN     NaN
65628          2020  Centro-Oeste    DF  ...      5.1     NaN     NaN
65629          2020  Centro-Oeste    DF  ...      5.1     NaN     NaN
65630          2020  Centro-Oeste    DF  ...      5.6     NaN     NaN

[65631 rows x 28 columns]

In [16]:
ha20New.dtypes

8
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
CO_MUNICIPIO      int64
NO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
HAD_INF         float64
HAD_CRE         float64
HAD_PRE         float64
HAD_FUN         float64
HAD_F14         float64
HAD_F58         float64
HAD_F00         float64
HAD_F01         float64
HAD_F02         float64
HAD_F03         float64
HAD_F04         float64
HAD_F05         float64
HAD_F06         float64
HAD_F07         float64
HAD_F08         float64
HAD_MED         float64
HAD_M01         float64
HAD_M02         float64
HAD_M03         float64
HAD_M04         float64
HAD_MNS         float64
dtype: object

In [17]:
haTot = pd.concat([ha16New,ha17New,ha18New,ha19New,ha20New])
haTot

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2016         Norte    RO  ...      4.6     NaN     NaN
1              2016         Norte    RO  ...      4.6     NaN     NaN
2              2016         Norte    RO  ...      NaN     NaN     NaN
3              2016         Norte    RO  ...      4.6     NaN     NaN
4              2016         Norte    RO  ...      4.6     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
65626          2020  Centro-Oeste    DF  ...      5.6     NaN     5.3
65627          2020  Centro-Oeste    DF  ...      5.8     NaN     NaN
65628          2020  Centro-Oeste    DF  ...      5.1     NaN     NaN
65629          2020  Centro-Oeste    DF  ...      5.1     NaN     NaN
65630          2020  Centro-Oeste    DF  ...      5.6     NaN     NaN

[328748 rows x 28 columns]

In [41]:
haTot = haTot[haTot["NO_REGIAO"] == "Sudeste"]
haTot.reset_index(drop=True, inplace=True)
haTot

8      NU_ANO_CENSO NO_REGIAO SG_UF  ...  HAD_M03 HAD_M04 HAD_MNS
0              2016   Sudeste    MG  ...      4.5     4.5     NaN
1              2016   Sudeste    MG  ...      4.5     4.5     NaN
2              2016   Sudeste    MG  ...      NaN     NaN     NaN
3              2016   Sudeste    MG  ...      4.5     4.5     NaN
4              2016   Sudeste    MG  ...      4.5     4.5     NaN
...             ...       ...   ...  ...      ...     ...     ...
93508          2020   Sudeste    SP  ...      NaN     NaN     NaN
93509          2020   Sudeste    SP  ...      NaN     NaN     NaN
93510          2020   Sudeste    SP  ...      NaN     NaN     NaN
93511          2020   Sudeste    SP  ...      5.1     NaN     NaN
93512          2020   Sudeste    SP  ...      5.1     NaN     NaN

[93513 rows x 28 columns]

In [49]:
compression_opts = dict(method='zip',
                        archive_name='horas_aula_completo.csv')  
haTot.to_csv('horas_aula_completo.zip', index=True,
          compression=compression_opts)

In [44]:
haTot.to_excel('horas_aula_completo.xlsx', index=True)

# Organizando e entendendo Dados de Alunos por Turma
## 2016 - 2020

In [21]:
at16 = pd.read_excel("/content/alunos_turma_2016.xlsx", index_col=False, header=None, squeeze=True)
at16

                                                      0   ...    28
0                                                    NaN  ...   NaN
1                                                    NaN  ...   NaN
2                                                    NaN  ...   NaN
3                                                    ...  ...   NaN
4      Média de Alunos por Turma da Educação Básica -...  ...   NaN
...                                                  ...  ...   ...
66630                                               2016  ...  35.6
66631                                               2016  ...    --
66632                                                NaN  ...   NaN
66633         Fonte: Censo da Educação Básica 2016/INEP.  ...   NaN
66634  Nota: 1)  Indicador calculado para as turmas U...  ...   NaN

[66635 rows x 29 columns]

In [22]:
at16New = at16
at16New.columns = at16.iloc[8]
at16New = at16.drop(labels=[0,1,2,3,4,5,6,7,8,66632,66633,66634], axis=0)
at16New = at16New.replace("--", np.nan, regex=True)
at16New.reset_index(drop=True, inplace=True)
at16New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2016         Norte    RO  ...     20.3     NaN     NaN
1              2016         Norte    RO  ...     20.3     NaN     NaN
2              2016         Norte    RO  ...      NaN     NaN     NaN
3              2016         Norte    RO  ...     20.3     NaN     NaN
4              2016         Norte    RO  ...     20.3     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66618          2016  Centro-Oeste    DF  ...     34.8     5.0     NaN
66619          2016  Centro-Oeste    DF  ...     37.7     NaN     NaN
66620          2016  Centro-Oeste    DF  ...     33.8     NaN    35.6
66621          2016  Centro-Oeste    DF  ...     34.1     NaN    35.6
66622          2016  Centro-Oeste    DF  ...     25.4     NaN     NaN

[66623 rows x 29 columns]

In [23]:
at16New.dtypes

8
NU_ANO_CENSO       int64
NO_REGIAO         object
SG_UF             object
CO_MUNICIPIO       int64
NO_MUNICIPIO      object
TIPOLOCA          object
Dependad          object
ATU_INF          float64
ATU_CRE          float64
ATU_PRE          float64
ATU_FUN          float64
ATU_F14          float64
ATU_F58          float64
ATU_F00          float64
ATU_F01          float64
ATU_F02          float64
ATU_F03          float64
ATU_F04          float64
ATU_F05          float64
ATU_F06          float64
ATU_F07          float64
ATU_F08          float64
ATU_UNIFICADA    float64
ATU_MED          float64
ATU_M01          float64
ATU_M02          float64
ATU_M03          float64
ATU_M04          float64
ATU_MNS          float64
dtype: object

In [24]:
at17 = pd.read_excel("/content/alunos_turma_2017.xlsx", index_col=False, header=None, squeeze=True)
at17

                                                      0   ...   28
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Média de Alunos por Turma da Educação Básica -...  ...  NaN
...                                                  ...  ...  ...
66604                                               2017  ...   --
66605                                               2017  ...   --
66606                                                NaN  ...  NaN
66607         Fonte: Censo da Educação Básica 2017/INEP.  ...  NaN
66608  Notas: 1) - Inclusive turmas Unificadas.\n    ...  ...  NaN

[66609 rows x 29 columns]

In [25]:
at17New = at17
at17New.columns = at17.iloc[8]
at17New = at17.drop(labels=[0,1,2,3,4,5,6,7,8,66606,66607,66608], axis=0)
at17New = at17New.replace("--", np.nan, regex=True)
at17New.reset_index(drop=True, inplace=True)
at17New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2017         Norte    RO  ...     19.8     NaN     NaN
1              2017         Norte    RO  ...     19.8     NaN     NaN
2              2017         Norte    RO  ...      NaN     NaN     NaN
3              2017         Norte    RO  ...     19.8     NaN     NaN
4              2017         Norte    RO  ...     19.8     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66592          2017  Centro-Oeste    DF  ...     33.8     NaN     NaN
66593          2017  Centro-Oeste    DF  ...     42.0     NaN     NaN
66594          2017  Centro-Oeste    DF  ...     33.4     NaN     NaN
66595          2017  Centro-Oeste    DF  ...     33.6     NaN     NaN
66596          2017  Centro-Oeste    DF  ...     26.9     NaN     NaN

[66597 rows x 29 columns]

In [26]:
at17New.dtypes

8
NU_ANO_CENSO       int64
NO_REGIAO         object
SG_UF             object
CO_MUNICIPIO       int64
NO_MUNICIPIO      object
TIPOLOCA          object
Dependad          object
ATU_INF          float64
ATU_CRE          float64
ATU_PRE          float64
ATU_FUN          float64
ATU_F14          float64
ATU_F58          float64
ATU_F00          float64
ATU_F01          float64
ATU_F02          float64
ATU_F03          float64
ATU_F04          float64
ATU_F05          float64
ATU_F06          float64
ATU_F07          float64
ATU_F08          float64
ATU_UNIFICADA    float64
ATU_MED          float64
ATU_M01          float64
ATU_M02          float64
ATU_M03          float64
ATU_M04          float64
ATU_MNS          float64
dtype: object

In [27]:
at18 = pd.read_excel("/content/alunos_turma_2018.xlsx", index_col=False, header=None, squeeze=True)
at18

                                                      0   ...   28
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Média de Alunos por Turma da Educação Básica -...  ...  NaN
...                                                  ...  ...  ...
66754                                               2018  ...   --
66755                                               2018  ...   --
66756                                                NaN  ...  NaN
66757         Fonte: Censo da Educação Básica 2018/INEP.  ...  NaN
66758  Notas: 1) - Inclusive turmas Unificadas.\n    ...  ...  NaN

[66759 rows x 29 columns]

In [28]:
at18New = at18
at18New.columns = at18.iloc[8]
at18New = at18.drop(labels=[0,1,2,3,4,5,6,7,8,66756,66757,66758], axis=0)
at18New = at18New.replace("--", np.nan, regex=True)
at18New.reset_index(drop=True, inplace=True)
at18New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2018         Norte    RO  ...     13.9     NaN     NaN
1              2018         Norte    RO  ...     14.8     NaN     NaN
2              2018         Norte    RO  ...      4.0     NaN     NaN
3              2018         Norte    RO  ...     13.9     NaN     NaN
4              2018         Norte    RO  ...     14.8     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66742          2018  Centro-Oeste    DF  ...     33.5     NaN    33.0
66743          2018  Centro-Oeste    DF  ...     46.0     NaN     NaN
66744          2018  Centro-Oeste    DF  ...     32.7     NaN     NaN
66745          2018  Centro-Oeste    DF  ...     33.0     NaN     NaN
66746          2018  Centro-Oeste    DF  ...     26.2     NaN     NaN

[66747 rows x 29 columns]

In [29]:
at18New.dtypes

8
NU_ANO_CENSO       int64
NO_REGIAO         object
SG_UF             object
CO_MUNICIPIO       int64
NO_MUNICIPIO      object
TIPOLOCA          object
Dependad          object
ATU_INF          float64
ATU_CRE          float64
ATU_PRE          float64
ATU_FUN          float64
ATU_F14          float64
ATU_F04          float64
ATU_F58          float64
ATU_F00          float64
ATU_F01          float64
ATU_F02          float64
ATU_F03          float64
ATU_F05          float64
ATU_F06          float64
ATU_F07          float64
ATU_F08          float64
ATU_UNIFICADA    float64
ATU_MED          float64
ATU_M01          float64
ATU_M02          float64
ATU_M03          float64
ATU_M04          float64
ATU_MNS          float64
dtype: object

In [30]:
at19 = pd.read_excel("/content/alunos_turma_2019.xlsx", index_col=False, header=None, squeeze=True)
at19

                                                      0   ...   28
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Média de Alunos por Turma da Educação Básica -...  ...  NaN
...                                                  ...  ...  ...
66688                                               2019  ...   --
66689                                               2019  ...   --
66690                                                NaN  ...  NaN
66691         Fonte: Censo da Educação Básica 2019/INEP.  ...  NaN
66692  Notas: 1) - Inclusive turmas Unificadas.\n    ...  ...  NaN

[66693 rows x 29 columns]

In [31]:
at19New = at19
at19New.columns = at18.iloc[8]
at19New = at19.drop(labels=[0,1,2,3,4,5,6,7,8,66690,66691,66692], axis=0)
at19New = at19New.replace("--", np.nan, regex=True)
at19New.reset_index(drop=True, inplace=True)
at19New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2019         Norte    RO  ...     14.4     NaN     NaN
1              2019         Norte    RO  ...     15.5     NaN     NaN
2              2019         Norte    RO  ...      6.0     NaN     NaN
3              2019         Norte    RO  ...     14.4     NaN     NaN
4              2019         Norte    RO  ...     15.5     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66676          2019  Centro-Oeste    DF  ...     32.6     NaN    47.0
66677          2019  Centro-Oeste    DF  ...     49.0     NaN     NaN
66678          2019  Centro-Oeste    DF  ...     33.4     NaN     NaN
66679          2019  Centro-Oeste    DF  ...     33.6     NaN     NaN
66680          2019  Centro-Oeste    DF  ...     26.5     NaN     NaN

[66681 rows x 29 columns]

In [32]:
at19New.dtypes

8
NU_ANO_CENSO       int64
NO_REGIAO         object
SG_UF             object
CO_MUNICIPIO       int64
NO_MUNICIPIO      object
TIPOLOCA          object
Dependad          object
ATU_INF          float64
ATU_CRE          float64
ATU_PRE          float64
ATU_FUN          float64
ATU_F14          float64
ATU_F04          float64
ATU_F58          float64
ATU_F00          float64
ATU_F01          float64
ATU_F02          float64
ATU_F03          float64
ATU_F05          float64
ATU_F06          float64
ATU_F07          float64
ATU_F08          float64
ATU_UNIFICADA    float64
ATU_MED          float64
ATU_M01          float64
ATU_M02          float64
ATU_M03          float64
ATU_M04          float64
ATU_MNS          float64
dtype: object

In [33]:
at20 = pd.read_excel("/content/alunos_turma_2020.xlsx", index_col=False, header=None, squeeze=True)
at20

                                                      0   ...   28
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Média de Alunos por Turma da Educação Básica -...  ...  NaN
...                                                  ...  ...  ...
66641                                               2020  ...   --
66642                                               2020  ...   --
66643                                                NaN  ...  NaN
66644         Fonte: Censo da Educação Básica 2020/INEP.  ...  NaN
66645  Notas: 1) - Inclusive turmas Unificadas.\n    ...  ...  NaN

[66646 rows x 29 columns]

In [34]:
at20New = at20
at20New.columns = at18.iloc[8]
at20New = at20.drop(labels=[0,1,2,3,4,5,6,7,8,66643,66644,66645], axis=0)
at20New = at20New.replace("--", np.nan, regex=True)
at20New.reset_index(drop=True, inplace=True)
at20New

8      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2020         Norte    RO  ...     13.4     NaN     NaN
1              2020         Norte    RO  ...     14.4     NaN     NaN
2              2020         Norte    RO  ...      6.5     NaN     NaN
3              2020         Norte    RO  ...     13.4     NaN     NaN
4              2020         Norte    RO  ...     14.4     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66629          2020  Centro-Oeste    DF  ...     33.6     NaN    39.0
66630          2020  Centro-Oeste    DF  ...     40.5     NaN     NaN
66631          2020  Centro-Oeste    DF  ...     34.0     NaN     NaN
66632          2020  Centro-Oeste    DF  ...     34.2     NaN     NaN
66633          2020  Centro-Oeste    DF  ...     27.2     NaN     NaN

[66634 rows x 29 columns]

In [35]:
at20New.dtypes

8
NU_ANO_CENSO       int64
NO_REGIAO         object
SG_UF             object
CO_MUNICIPIO       int64
NO_MUNICIPIO      object
TIPOLOCA          object
Dependad          object
ATU_INF          float64
ATU_CRE          float64
ATU_PRE          float64
ATU_FUN          float64
ATU_F14          float64
ATU_F04          float64
ATU_F58          float64
ATU_F00          float64
ATU_F01          float64
ATU_F02          float64
ATU_F03          float64
ATU_F05          float64
ATU_F06          float64
ATU_F07          float64
ATU_F08          float64
ATU_UNIFICADA    float64
ATU_MED          float64
ATU_M01          float64
ATU_M02          float64
ATU_M03          float64
ATU_M04          float64
ATU_MNS          float64
dtype: object

In [36]:
atTot = pd.concat([at16New,at17New,at18New,at19New,at20New])
atTot

       NU_ANO_CENSO     NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2016         Norte    RO  ...     20.3     NaN     NaN
1              2016         Norte    RO  ...     20.3     NaN     NaN
2              2016         Norte    RO  ...      NaN     NaN     NaN
3              2016         Norte    RO  ...     20.3     NaN     NaN
4              2016         Norte    RO  ...     20.3     NaN     NaN
...             ...           ...   ...  ...      ...     ...     ...
66629          2020  Centro-Oeste    DF  ...     33.6     NaN    39.0
66630          2020  Centro-Oeste    DF  ...     40.5     NaN     NaN
66631          2020  Centro-Oeste    DF  ...     34.0     NaN     NaN
66632          2020  Centro-Oeste    DF  ...     34.2     NaN     NaN
66633          2020  Centro-Oeste    DF  ...     27.2     NaN     NaN

[333282 rows x 29 columns]

In [40]:
atTot = atTot[atTot["NO_REGIAO"] == "Sudeste"]
atTot.reset_index(drop=True, inplace=True)
atTot

       NU_ANO_CENSO NO_REGIAO SG_UF  ...  ATU_M03 ATU_M04 ATU_MNS
0              2016   Sudeste    MG  ...     30.0    27.0     NaN
1              2016   Sudeste    MG  ...     30.0    27.0     NaN
2              2016   Sudeste    MG  ...      NaN     NaN     NaN
3              2016   Sudeste    MG  ...     30.0    27.0     NaN
4              2016   Sudeste    MG  ...     30.0    27.0     NaN
...             ...       ...   ...  ...      ...     ...     ...
94843          2020   Sudeste    SP  ...      NaN     NaN     NaN
94844          2020   Sudeste    SP  ...      NaN     NaN     NaN
94845          2020   Sudeste    SP  ...      NaN     NaN     NaN
94846          2020   Sudeste    SP  ...     29.7     NaN     NaN
94847          2020   Sudeste    SP  ...     29.7     NaN     NaN

[94848 rows x 29 columns]

In [50]:
compression_opts = dict(method='zip',
                        archive_name='alunos_turma_completo.csv')  
atTot.to_csv('alunos_turma_completo.zip', index=True,
          compression=compression_opts)

In [51]:
atTot.to_excel('alunos_turma_completo.xlsx', index=True)

# Organizando e entendendo Formação dos Docentes
## 2016 - 2020

In [52]:
ds16 = pd.read_excel("/content/docentes_superior_2016.xlsx", index_col=False, header=None, squeeze=True)
ds16

                                                      0   ...    16
0                                                    NaN  ...   NaN
1                                                    NaN  ...   NaN
2                                                    NaN  ...   NaN
3                                                    ...  ...   NaN
4      Percentual de Docentes com Curso Superior na E...  ...   NaN
...                                                  ...  ...   ...
67824                                               2016  ...    --
67825                                               2016  ...  94.5
67826                                               2016  ...  94.4
67827                                               2016  ...   100
67828                                                NaN  ...    --

[67829 rows x 17 columns]

In [53]:
ds16New = ds16
ds16New.columns = ds16.iloc[9]
ds16New = ds16New.drop(labels=[0,1,2,3,4,5,6,7,8,9], axis=0)
ds16New = ds16New[ds16New.index < 67828]
ds16New = ds16New.replace("--", np.nan, regex=True)
ds16New.reset_index(drop=True, inplace=True)
ds16New

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  DSU_PROF DSU_EJA DSU_ESP
0              2016         Norte    RO  ...       NaN    91.2   100.0
1              2016         Norte    RO  ...       NaN    91.2   100.0
2              2016         Norte    RO  ...       NaN     NaN     NaN
3              2016         Norte    RO  ...       NaN    91.2     NaN
4              2016         Norte    RO  ...       NaN    91.2     NaN
...             ...           ...   ...  ...       ...     ...     ...
67813          2016  Centro-Oeste    DF  ...      85.0    95.0    89.8
67814          2016  Centro-Oeste    DF  ...     100.0     NaN     NaN
67815          2016  Centro-Oeste    DF  ...      99.2    98.8    94.5
67816          2016  Centro-Oeste    DF  ...      99.1    98.9    94.4
67817          2016  Centro-Oeste    DF  ...     100.0    97.6   100.0

[67818 rows x 17 columns]

In [54]:
ds16New.dtypes

9
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
NO_MUNICIPIO      int64
CO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
DSU_INF         float64
DSU_CRE         float64
DSU_PRE         float64
DSU_FUN         float64
DSU_F14         float64
DSU_F58         float64
DSU_MED         float64
DSU_PROF        float64
DSU_EJA         float64
DSU_ESP         float64
dtype: object

In [55]:
ds17 = pd.read_excel("/content/docentes_superior_2017.xlsx", index_col=False, header=None, squeeze=True)
ds17

                                                      0   ...    16
0                                                    NaN  ...   NaN
1                                                    NaN  ...   NaN
2                                                    NaN  ...   NaN
3                                                    ...  ...   NaN
4      Percentual de Docentes com Curso Superior na E...  ...   NaN
...                                                  ...  ...   ...
67692                                               2017  ...  95.2
67693                                               2017  ...  95.1
67694                                               2017  ...   100
67695                                                NaN  ...    --
67696         Fonte: Censo da Educação Básica 2017/INEP.  ...   NaN

[67697 rows x 17 columns]

In [56]:
ds17New = ds17
ds17New.columns = ds17.iloc[9]
ds17New = ds17New.drop(labels=[0,1,2,3,4,5,6,7,8,9], axis=0)
ds17New = ds17New[ds17New.index < 67695]
ds17New = ds17New.replace("--", np.nan, regex=True)
ds17New.reset_index(drop=True, inplace=True)
ds17New

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  DSU_PROF DSU_EJA DSU_ESP
0              2017         Norte    RO  ...       NaN    93.1   100.0
1              2017         Norte    RO  ...       NaN    93.1   100.0
2              2017         Norte    RO  ...       NaN     NaN     NaN
3              2017         Norte    RO  ...       NaN    93.1     NaN
4              2017         Norte    RO  ...       NaN    93.1     NaN
...             ...           ...   ...  ...       ...     ...     ...
67680          2017  Centro-Oeste    DF  ...      85.0    92.5    91.2
67681          2017  Centro-Oeste    DF  ...      50.0     NaN     NaN
67682          2017  Centro-Oeste    DF  ...      99.2    98.5    95.2
67683          2017  Centro-Oeste    DF  ...      99.1    98.5    95.1
67684          2017  Centro-Oeste    DF  ...     100.0    98.3   100.0

[67685 rows x 17 columns]

In [57]:
ds17New.dtypes

9
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
NO_MUNICIPIO      int64
CO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
DSU_INF         float64
DSU_CRE         float64
DSU_PRE         float64
DSU_FUN         float64
DSU_F14         float64
DSU_F58         float64
DSU_MED         float64
DSU_PROF        float64
DSU_EJA         float64
DSU_ESP         float64
dtype: object

In [58]:
ds18 = pd.read_excel("/content/docentes_superior_2018.xlsx", index_col=False, header=None, squeeze=True)
ds18

                                                      0   ...   16
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Percentual de Funções Docentes com Curso Super...  ...  NaN
...                                                  ...  ...  ...
67659                                               2018  ...  100
67660                                               2018  ...  NaN
67661                                               2018  ...  100
67662                                                NaN  ...   --
67663         Fonte: Censo da Educação Básica 2018/INEP.  ...  NaN

[67664 rows x 17 columns]

In [59]:
ds18New = ds18
ds18New.columns = ds17.iloc[9]
ds18New = ds18New.drop(labels=[0,1,2,3,4,5,6,7,8,9], axis=0)
ds18New = ds18New[ds18New.index < 67662]
ds18New = ds18New.replace("--", np.nan, regex=True)
ds18New.reset_index(drop=True, inplace=True)
ds18New

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ... DSU_PROF DSU_EJA DSU_ESP
0              2018         Norte    RO  ...      NaN    94.4   100.0
1              2018         Norte    RO  ...      NaN    94.4     NaN
2              2018         Norte    RO  ...      NaN     NaN     NaN
3              2018         Norte    RO  ...      NaN     NaN   100.0
4              2018         Norte    RO  ...      NaN    94.4     NaN
...             ...           ...   ...  ...      ...     ...     ...
67647          2018  Centro-Oeste    DF  ...     97.7    96.6   100.0
67648          2018  Centro-Oeste    DF  ...    100.0     NaN     NaN
67649          2018  Centro-Oeste    DF  ...      NaN    96.6   100.0
67650          2018  Centro-Oeste    DF  ...     75.0     NaN     NaN
67651          2018  Centro-Oeste    DF  ...    100.0    96.6   100.0

[67652 rows x 17 columns]

In [60]:
ds18New.dtypes

9
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
NO_MUNICIPIO     object
CO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
DSU_INF         float64
DSU_CRE         float64
DSU_PRE         float64
DSU_FUN         float64
DSU_F14         float64
DSU_F58         float64
DSU_MED         float64
DSU_PROF        float64
DSU_EJA         float64
DSU_ESP         float64
dtype: object

In [61]:
ds19 = pd.read_excel("/content/docentes_superior_2019.xlsx", index_col=False, header=None, squeeze=True)
ds19

                                                      0   ...   16
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Percentual de Funções Docentes com Curso Super...  ...  NaN
...                                                  ...  ...  ...
67516                                               2019  ...  100
67517                                               2019  ...  NaN
67518                                               2019  ...  100
67519                                                NaN  ...   --
67520         Fonte: Censo da Educação Básica 2019/INEP.  ...  NaN

[67521 rows x 17 columns]

In [62]:
ds19New = ds19
ds19New.columns = ds17.iloc[9]
ds19New = ds19New.drop(labels=[0,1,2,3,4,5,6,7,8,9], axis=0)
ds19New = ds19New[ds19New.index < 67519]
ds19New = ds19New.replace("--", np.nan, regex=True)
ds19New.reset_index(drop=True, inplace=True)
ds19New

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ... DSU_PROF DSU_EJA DSU_ESP
0              2019         Norte    RO  ...      NaN   100.0     NaN
1              2019         Norte    RO  ...      NaN   100.0     NaN
2              2019         Norte    RO  ...      NaN     NaN     NaN
3              2019         Norte    RO  ...      NaN   100.0     NaN
4              2019         Norte    RO  ...      NaN   100.0     NaN
...             ...           ...   ...  ...      ...     ...     ...
67504          2019  Centro-Oeste    DF  ...     97.9    98.1   100.0
67505          2019  Centro-Oeste    DF  ...     97.7   100.0     NaN
67506          2019  Centro-Oeste    DF  ...      NaN    97.9   100.0
67507          2019  Centro-Oeste    DF  ...    100.0     NaN     NaN
67508          2019  Centro-Oeste    DF  ...     97.7    98.1   100.0

[67509 rows x 17 columns]

In [63]:
ds19New.dtypes

9
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
NO_MUNICIPIO     object
CO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
DSU_INF         float64
DSU_CRE         float64
DSU_PRE         float64
DSU_FUN         float64
DSU_F14         float64
DSU_F58         float64
DSU_MED         float64
DSU_PROF        float64
DSU_EJA         float64
DSU_ESP         float64
dtype: object

In [64]:
ds20 = pd.read_excel("/content/docentes_superior_2020.xlsx", index_col=False, header=None, squeeze=True)
ds20

                                                      0   ...   16
0                                                    NaN  ...  NaN
1                                                    NaN  ...  NaN
2                                                    NaN  ...  NaN
3                                                    ...  ...  NaN
4      Percentual de Funções Docentes com Curso Super...  ...  NaN
...                                                  ...  ...  ...
67454                                               2020  ...  100
67455                                               2020  ...   --
67456                                               2020  ...  100
67457                                                NaN  ...   --
67458         Fonte: Censo da Educação Básica 2020/INEP.  ...  NaN

[67459 rows x 17 columns]

In [65]:
ds20New = ds20
ds20New.columns = ds17.iloc[9]
ds20New = ds20New.drop(labels=[0,1,2,3,4,5,6,7,8,9], axis=0)
ds20New = ds20New[ds20New.index < 67457]
ds20New = ds20New.replace("--", np.nan, regex=True)
ds20New.reset_index(drop=True, inplace=True)
ds20New

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ...  DSU_PROF DSU_EJA DSU_ESP
0              2020         Norte    RO  ...       NaN   100.0     NaN
1              2020         Norte    RO  ...       NaN   100.0     NaN
2              2020         Norte    RO  ...       NaN     NaN     NaN
3              2020         Norte    RO  ...       NaN   100.0     NaN
4              2020         Norte    RO  ...       NaN   100.0     NaN
...             ...           ...   ...  ...       ...     ...     ...
67442          2020  Centro-Oeste    DF  ...     100.0   100.0   100.0
67443          2020  Centro-Oeste    DF  ...     100.0   100.0     NaN
67444          2020  Centro-Oeste    DF  ...       NaN   100.0   100.0
67445          2020  Centro-Oeste    DF  ...     100.0     NaN     NaN
67446          2020  Centro-Oeste    DF  ...     100.0   100.0   100.0

[67447 rows x 17 columns]

In [66]:
ds20New.dtypes

9
NU_ANO_CENSO      int64
NO_REGIAO        object
SG_UF            object
NO_MUNICIPIO      int64
CO_MUNICIPIO     object
TIPOLOCA         object
Dependad         object
DSU_INF         float64
DSU_CRE         float64
DSU_PRE         float64
DSU_FUN         float64
DSU_F14         float64
DSU_F58         float64
DSU_MED         float64
DSU_PROF        float64
DSU_EJA         float64
DSU_ESP         float64
dtype: object

In [67]:
dsTot = pd.concat([ds16New,ds17New,ds18New,ds19New,ds20New])
dsTot

9      NU_ANO_CENSO     NO_REGIAO SG_UF  ... DSU_PROF DSU_EJA DSU_ESP
0              2016         Norte    RO  ...      NaN    91.2   100.0
1              2016         Norte    RO  ...      NaN    91.2   100.0
2              2016         Norte    RO  ...      NaN     NaN     NaN
3              2016         Norte    RO  ...      NaN    91.2     NaN
4              2016         Norte    RO  ...      NaN    91.2     NaN
...             ...           ...   ...  ...      ...     ...     ...
67442          2020  Centro-Oeste    DF  ...    100.0   100.0   100.0
67443          2020  Centro-Oeste    DF  ...    100.0   100.0     NaN
67444          2020  Centro-Oeste    DF  ...      NaN   100.0   100.0
67445          2020  Centro-Oeste    DF  ...    100.0     NaN     NaN
67446          2020  Centro-Oeste    DF  ...    100.0   100.0   100.0

[338111 rows x 17 columns]

In [68]:
dsTot = dsTot[dsTot["NO_REGIAO"] == "Sudeste"]
dsTot.reset_index(drop=True, inplace=True)
dsTot

9      NU_ANO_CENSO NO_REGIAO SG_UF  ... DSU_PROF DSU_EJA DSU_ESP
0              2016   Sudeste    MG  ...      NaN   100.0    83.3
1              2016   Sudeste    MG  ...      NaN   100.0    83.3
2              2016   Sudeste    MG  ...      NaN     NaN     NaN
3              2016   Sudeste    MG  ...      NaN   100.0     NaN
4              2016   Sudeste    MG  ...      NaN   100.0     NaN
...             ...       ...   ...  ...      ...     ...     ...
96385          2020   Sudeste    SP  ...      NaN   100.0   100.0
96386          2020   Sudeste    SP  ...      NaN   100.0     NaN
96387          2020   Sudeste    SP  ...      NaN     NaN     NaN
96388          2020   Sudeste    SP  ...      NaN     NaN   100.0
96389          2020   Sudeste    SP  ...      NaN   100.0     NaN

[96390 rows x 17 columns]

In [69]:
compression_opts = dict(method='zip',
                        archive_name='docentes_superior_completo.csv')  
dsTot.to_csv('docentes_superior_completo.zip', index=True,
          compression=compression_opts)

In [70]:
dsTot.to_excel('docentes_superior_completo.xlsx', index=True)